//1.bUATLAH PROGRAM DIBAWAH INI
#include <conio.h>
#include <iostream.h>

void main ()
{
	clrscr();
   cout << "it is my first C++ program\n";
   cout << "I am sure that i will be familiar with this";
   cout << "-------------------------------------\n";

//2.3 huruf terdepan dari nama anda DEV
   cout << "DDDDDDDDD     EEEEEEEEEE   VV              VV	"<<endl ;
   cout << "DDDDDDDDD     EEEEEEEEEE    VV            VV		"<<endl ;
   cout << "DD     DD     EE             VV          VV		"<<endl ;
   cout << "DD     DD     EEEEEEEEEE      VV        VV		"<<endl ;
   cout << "DD     DD     EEEEEEEEEE       VV      VV			"<<endl ;
   cout << "DD     DD     EE                VV    VV			"<<endl ;
   cout << "DDDDDDDDD     EEEEEEEEEE         VV  VV				"<<endl ;
   cout << "DDDDDDDDD     EEEEEEEEEE           VV   			"<<endl ;
   getch ();
}