#include <stdio.h>    // ini adalah  header untuk fungsi printf
#include <iostream>   // ini adalah header untuk fungsi cout
#include <conio.h>    // ini adalah header untuk clscr dan getch
int main()           // program bagian utama bisa void main
{
clrscr ();
printf ( " Hello world.\n") ; // n berguna untuk pindah baris
cout << " HIE HIE HIE " ;
cout << "/n Hallo....selamat datang...";//posisi n di depan maka kursor disamping
cout <<endl<< " Nama Saya"<<endl<< "Devi Chungiarto" ; //endl mirip dengan n
getch () ;
return 0 ;
}

